### PR TITLE
Remove config-artifact-bucket.yaml

### PR DESCRIPTION
**Pull request by abayer**
This requires additional configuration to actually be useable - as is,
it'll just make every attempt to use `output` on a `Task` fail. Better
for now to fall back on the no-configuration-needed PVC approach,
which just works out of the box without any effort.

cc @rawlingsj @jstrachan @dwnusbaum

### CODE REVIEW

**Comment by rawlingsj** [comment]
Pretty sure we needed that to avoid the controller crashing.  It's worth checking if you can delete the `config-artifact-bucket` configmap and bounce the pipeline controller and webhook pods to check they can start again?

**Comment by abayer** [comment]
Lemme see.

**Comment by abayer** [comment]
Blech, you're right. Lemme see how I can work around this.

**Comment by abayer** [comment]
Aaaah, this is https://github.com/knative/build-pipeline/pull/475 so we'll need to wait for that.

**Pull request closed without merging**
